/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: jetty/12.0.7
 * Generated at: 2026-05-13 08:11:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.fournisseur;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class liste_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:substring", org.apache.taglibs.standard.functions.Functions.class, "substring", new Class[] {java.lang.String.class, int.class, int.class});
}

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/Users/COMPUTER%20STORES/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/fn.tld", Long.valueOf(1664446278000L));
    _jspx_dependants.put("file:/C:/Users/COMPUTER%20STORES/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1778365320317L));
    _jspx_dependants.put("jar:file:/C:/Users/COMPUTER%20STORES/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld", Long.valueOf(1664446278000L));
    _jspx_dependants.put("/views/partials/head.jspf", Long.valueOf(1778659006971L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"fr\">\n");
      out.write("<head>\n");
      out.write("    ");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,600;9..144,700;9..144,800&family=Manrope:wght@400;500;600;700;800&display=swap\" rel=\"stylesheet\">\n");
      out.write("<script src=\"https://cdn.tailwindcss.com\"></script>\n");
      out.write("<script>\n");
      out.write("    tailwind.config = {\n");
      out.write("        theme: {\n");
      out.write("            extend: {\n");
      out.write("                fontFamily: {\n");
      out.write("                    sans: ['Manrope', 'sans-serif'],\n");
      out.write("                    display: ['Fraunces', 'serif']\n");
      out.write("                },\n");
      out.write("                colors: {\n");
      out.write("                    market: {\n");
      out.write("                        cream: \"#f4f8ff\",\n");
      out.write("                        parchment: \"#e8f0ff\",\n");
      out.write("                        pine: \"#1f3fb7\",\n");
      out.write("                        moss: \"#2448d8\",\n");
      out.write("                        mint: \"#d7e6ff\",\n");
      out.write("                        gold: \"#f5a000\",\n");
      out.write("                        ember: \"#ff4d4f\",\n");
      out.write("                        ink: \"#171d2d\",\n");
      out.write("                        line: \"#d7e4ff\",\n");
      out.write("                        shell: \"#fbfdff\"\n");
      out.write("                    }\n");
      out.write("                },\n");
      out.write("                boxShadow: {\n");
      out.write("                    panel: \"0 20px 60px rgba(30, 64, 208, 0.08)\",\n");
      out.write("                    float: \"0 14px 40px rgba(30, 64, 208, 0.12)\"\n");
      out.write("                },\n");
      out.write("                borderRadius: {\n");
      out.write("                    shell: \"2rem\"\n");
      out.write("                },\n");
      out.write("                backgroundImage: {\n");
      out.write("                    \"market-grid\": \"radial-gradient(circle at 1px 1px, rgba(31,63,183,0.08) 1px, transparent 0)\",\n");
      out.write("                    \"market-glow\": \"radial-gradient(circle at top right, rgba(245,160,0,0.18), transparent 32%), radial-gradient(circle at bottom left, rgba(36,72,216,0.12), transparent 30%)\"\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("</script>\n");
      out.write("<style>\n");
      out.write("    ::selection {\n");
      out.write("        background: rgba(36, 72, 216, 0.22);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    body {\n");
      out.write("        font-family: Manrope, sans-serif;\n");
      out.write("        background-image:\n");
      out.write("            radial-gradient(circle at top, rgba(255,255,255,0.92), transparent 30rem),\n");
      out.write("            linear-gradient(180deg, #f7fbff 0%, #eff5ff 100%);\n");
      out.write("        color: #171d2d;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .glass-panel {\n");
      out.write("        background: rgba(255, 255, 255, 0.9);\n");
      out.write("        backdrop-filter: blur(18px);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .app-shell {\n");
      out.write("        min-height: 100vh;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .sidebar-link {\n");
      out.write("        display: flex;\n");
      out.write("        align-items: center;\n");
      out.write("        gap: 0.95rem;\n");
      out.write("        border-radius: 1.35rem;\n");
      out.write("        padding: 0.95rem 1rem;\n");
      out.write("        color: #262d42;\n");
      out.write("        transition: all 180ms ease;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .sidebar-link:hover {\n");
      out.write("        background: #eef4ff;\n");
      out.write("        color: #1f3fb7;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .sidebar-link.active {\n");
      out.write("        background: #d8e7ff;\n");
      out.write("        color: #1f3fb7;\n");
      out.write("        box-shadow: inset 0 0 0 1px rgba(31, 63, 183, 0.06);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .sidebar-icon {\n");
      out.write("        flex-shrink: 0;\n");
      out.write("        width: 1.45rem;\n");
      out.write("        height: 1.45rem;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .page-card {\n");
      out.write("        border-radius: 2rem;\n");
      out.write("        border: 1px solid #d7e4ff;\n");
      out.write("        background: rgba(255, 255, 255, 0.95);\n");
      out.write("        box-shadow: 0 20px 60px rgba(30, 64, 208, 0.08);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .metric-card {\n");
      out.write("        position: relative;\n");
      out.write("        overflow: hidden;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .metric-card::after {\n");
      out.write("        content: \"\";\n");
      out.write("        position: absolute;\n");
      out.write("        inset: auto -10% -45% auto;\n");
      out.write("        width: 8rem;\n");
      out.write("        height: 8rem;\n");
      out.write("        border-radius: 9999px;\n");
      out.write("        background: rgba(255,255,255,0.08);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .blue-scroll::-webkit-scrollbar {\n");
      out.write("        width: 8px;\n");
      out.write("        height: 8px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .blue-scroll::-webkit-scrollbar-thumb {\n");
      out.write("        background: rgba(31, 63, 183, 0.3);\n");
      out.write("        border-radius: 9999px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .blue-scroll::-webkit-scrollbar-track {\n");
      out.write("        background: rgba(215, 228, 255, 0.55);\n");
      out.write("    }\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("    <title>Fournisseurs</title>\n");
      out.write("</head>\n");
      out.write("<body class=\"app-shell\">\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_c_005fset_005f2(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_c_005fset_005f3(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_c_005fset_005f4(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_c_005fset_005f5(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_c_005fset_005f6(_jspx_page_context))
        return;
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/views/partials/sidebar.jsp", out, false);
      out.write("\n");
      out.write("<div class=\"lg:pl-[19rem]\">\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/views/partials/topbar.jsp", out, false);
      out.write("\n");
      out.write("    <main class=\"space-y-8 px-4 py-6 sm:px-6 lg:px-10\">\n");
      out.write("        ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("        <section class=\"flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between\">\n");
      out.write("            <div>\n");
      out.write("                <p class=\"text-2xl font-semibold text-market-pine\">Gestion des Fournisseurs</p>\n");
      out.write("                <p class=\"mt-2 max-w-4xl text-2xl text-slate-500\">Gerez vos relations partenaires et suivez vos approvisionnements en temps reel.</p>\n");
      out.write("            </div>\n");
      out.write("            <a href=\"#add-supplier-form\" class=\"inline-flex items-center justify-center gap-3 rounded-[1.4rem] bg-market-pine px-8 py-5 text-2xl font-bold text-white shadow-float\">\n");
      out.write("                <span>+</span>\n");
      out.write("                <span>Nouveau Fournisseur</span>\n");
      out.write("            </a>\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("        <section class=\"grid gap-5 xl:grid-cols-4\">\n");
      out.write("            <article class=\"page-card border-l-4 border-l-market-pine p-8\">\n");
      out.write("                <p class=\"text-4xl uppercase tracking-tight text-market-ink\">Total Fournisseurs</p>\n");
      out.write("                <p class=\"mt-6 font-display text-5xl font-extrabold text-market-pine\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalFournisseurs}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\n");
      out.write("            </article>\n");
      out.write("            <article class=\"page-card border-l-4 border-l-market-gold p-8\">\n");
      out.write("                <p class=\"text-4xl uppercase tracking-tight text-market-ink\">Commandes actives</p>\n");
      out.write("                <p class=\"mt-6 font-display text-5xl font-extrabold text-market-gold\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${produitsEnAlerte.size()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\n");
      out.write("            </article>\n");
      out.write("            <article class=\"page-card border-l-4 border-l-market-moss p-8\">\n");
      out.write("                <p class=\"text-4xl uppercase tracking-tight text-market-ink\">Livraisons du jour</p>\n");
      out.write("                <p class=\"mt-6 font-display text-5xl font-extrabold text-market-moss\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fournisseurs.size()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\n");
      out.write("            </article>\n");
      out.write("            <article class=\"page-card border-l-4 border-l-red-400 p-8\">\n");
      out.write("                <p class=\"text-4xl uppercase tracking-tight text-market-ink\">Alertes rupture</p>\n");
      out.write("                <p class=\"mt-6 font-display text-5xl font-extrabold text-red-500\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${produitsEnAlerte.size()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\n");
      out.write("            </article>\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("        <section class=\"page-card p-6\">\n");
      out.write("            <form method=\"get\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/fournisseurs\" class=\"grid gap-4 lg:grid-cols-[1.5fr_repeat(3,minmax(0,1fr))]\">\n");
      out.write("                <input class=\"rounded-[1.3rem] border border-market-line bg-market-cream px-5 py-4 text-lg outline-none\" type=\"text\" name=\"search\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${search}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" placeholder=\"Raison sociale, telephone, email\">\n");
      out.write("                <select class=\"rounded-[1.3rem] border border-market-line bg-market-cream px-5 py-4 text-lg outline-none\" name=\"delai\">\n");
      out.write("                    <option value=\"\">Tous les delais</option>\n");
      out.write("                    <option value=\"fast\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${delai eq 'fast' ? 'selected' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Livraison rapide</option>\n");
      out.write("                    <option value=\"slow\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${delai eq 'slow' ? 'selected' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Delai long</option>\n");
      out.write("                </select>\n");
      out.write("                <select class=\"rounded-[1.3rem] border border-market-line bg-market-cream px-5 py-4 text-lg outline-none\" name=\"sort\">\n");
      out.write("                    <option value=\"raison_asc\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sort eq 'raison_asc' ? 'selected' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Nom A-Z</option>\n");
      out.write("                    <option value=\"delai_asc\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sort eq 'delai_asc' ? 'selected' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Delai croissant</option>\n");
      out.write("                    <option value=\"delai_desc\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sort eq 'delai_desc' ? 'selected' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(">Delai decroissant</option>\n");
      out.write("                </select>\n");
      out.write("                <div class=\"flex flex-wrap gap-3\">\n");
      out.write("                    <button class=\"rounded-[1.3rem] bg-market-pine px-6 py-4 text-lg font-bold text-white\" type=\"submit\">Filtrer</button>\n");
      out.write("                    <a class=\"rounded-[1.3rem] border border-market-line bg-white px-6 py-4 text-lg font-semibold text-slate-600\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/fournisseurs\">Reinitialiser</a>\n");
      out.write("                </div>\n");
      out.write("            </form>\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("        <section class=\"page-card overflow-hidden\">\n");
      out.write("            <div class=\"flex items-center justify-between gap-4 border-b border-market-line px-8 py-6\">\n");
      out.write("                <h2 class=\"font-display text-4xl font-bold text-market-pine\">Liste des Partenaires</h2>\n");
      out.write("                <div class=\"flex gap-3\">\n");
      out.write("                    <span class=\"rounded-[1.15rem] border border-market-line px-4 py-3 text-xl text-market-pine\">Filtrer</span>\n");
      out.write("                    <span class=\"rounded-[1.15rem] border border-market-line px-4 py-3 text-xl text-market-pine\">Exporter</span>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"overflow-x-auto\">\n");
      out.write("                <table class=\"min-w-[1180px] text-left\">\n");
      out.write("                    <thead class=\"border-b border-market-line bg-white text-2xl font-bold uppercase tracking-wide text-market-pine\">\n");
      out.write("                        <tr>\n");
      out.write("                            <th class=\"px-8 py-6\">Fournisseur</th>\n");
      out.write("                            <th class=\"px-8 py-6\">Contact</th>\n");
      out.write("                            <th class=\"px-8 py-6\">Categorie</th>\n");
      out.write("                            <th class=\"px-8 py-6\">Commandes</th>\n");
      out.write("                            <th class=\"px-8 py-6\">Actions</th>\n");
      out.write("                        </tr>\n");
      out.write("                    </thead>\n");
      out.write("                    <tbody>\n");
      out.write("                        ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                    </tbody>\n");
      out.write("                </table>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"flex flex-col gap-4 border-t border-market-line px-8 py-6 lg:flex-row lg:items-center lg:justify-between\">\n");
      out.write("                <p class=\"text-2xl text-slate-500\">Affichage de ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${((page - 1) * size) + 1}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('-');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${((page - 1) * size) + fournisseurs.size()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" sur ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalFiltered}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" fournisseurs</p>\n");
      out.write("                <div class=\"flex flex-wrap items-center gap-3 text-xl font-semibold\">\n");
      out.write("                    <a class=\"rounded-[1.15rem] border border-market-line px-5 py-3 ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page <= 1 ? 'pointer-events-none opacity-40' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/fournisseurs?search=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${search}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&delai=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${delai}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&sort=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sort}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&size=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${size}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&page=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page - 1}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Precedent</a>\n");
      out.write("                    <span class=\"rounded-[1.15rem] bg-market-pine px-5 py-3 text-white\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\n");
      out.write("                    <span class=\"rounded-[1.15rem] border border-market-line px-5 py-3\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalPages}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\n");
      out.write("                    <a class=\"rounded-[1.15rem] border border-market-line px-5 py-3 ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page >= totalPages ? 'pointer-events-none opacity-40' : ''}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/fournisseurs?search=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${search}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&delai=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${delai}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&sort=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sort}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&size=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${size}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&page=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${page + 1}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Suivant</a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("        <section class=\"grid gap-5 xl:grid-cols-[1.25fr_0.55fr]\">\n");
      out.write("            <article class=\"overflow-hidden rounded-[2rem] bg-market-pine p-8 text-white shadow-panel\">\n");
      out.write("                <h2 class=\"font-display text-4xl font-bold\">Optimisation des Stocks</h2>\n");
      out.write("                <p class=\"mt-6 max-w-4xl text-2xl leading-10 text-white/85\">L'algorithme suggere de commander 20% de stock supplementaire aupres des partenaires les plus fiables pour anticiper la demande.</p>\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/stock/alertes\" class=\"mt-8 inline-flex rounded-[1.3rem] bg-market-gold px-8 py-4 text-2xl font-bold text-white\">Consulter l'analyse</a>\n");
      out.write("            </article>\n");
      out.write("            <article class=\"page-card p-8 text-center\">\n");
      out.write("                <div class=\"mx-auto flex h-28 w-28 items-center justify-center rounded-full bg-market-mint text-market-pine\">\n");
      out.write("                    <svg class=\"h-12 w-12\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"1.9\"><circle cx=\"12\" cy=\"12\" r=\"9\"/><path d=\"M9.5 9a2.5 2.5 0 1 1 4.5 1.5c-.7 1-1.7 1.4-2 2.5\"/><path d=\"M12 17h.01\"/></svg>\n");
      out.write("                </div>\n");
      out.write("                <h3 class=\"mt-6 font-display text-4xl font-bold text-market-pine\">Support Partenaire</h3>\n");
      out.write("                <p class=\"mt-4 text-2xl leading-10 text-slate-500\">Une question sur vos integrations fournisseurs ?</p>\n");
      out.write("                <p class=\"mt-6 text-2xl font-bold text-market-pine\">Acceder au centre d'aide</p>\n");
      out.write("            </article>\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("        <section id=\"add-supplier-form\" class=\"page-card p-8\">\n");
      out.write("            <div class=\"mb-6\">\n");
      out.write("                <h2 class=\"font-display text-4xl font-bold text-market-pine\">Nouveau fournisseur</h2>\n");
      out.write("                <p class=\"mt-2 text-xl text-slate-500\">Ajout rapide d'un nouveau partenaire.</p>\n");
      out.write("            </div>\n");
      out.write("            <form method=\"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/fournisseurs/ajouter\" class=\"grid gap-4 md:grid-cols-2 xl:grid-cols-5\">\n");
      out.write("                <input class=\"rounded-[1.3rem] border border-market-line bg-market-cream px-5 py-4 text-lg outline-none\" type=\"text\" name=\"raisonSociale\" placeholder=\"Raison sociale\" required>\n");
      out.write("                <input class=\"rounded-[1.3rem] border border-market-line bg-market-cream px-5 py-4 text-lg outline-none\" type=\"text\" name=\"telephone\" placeholder=\"Telephone\">\n");
      out.write("                <input class=\"rounded-[1.3rem] border border-market-line bg-market-cream px-5 py-4 text-lg outline-none\" type=\"email\" name=\"email\" placeholder=\"Email\">\n");
      out.write("                <input class=\"rounded-[1.3rem] border border-market-line bg-market-cream px-5 py-4 text-lg outline-none\" type=\"number\" name=\"delaiLivraisonJours\" placeholder=\"Delai livraison\">\n");
      out.write("                <div class=\"xl:col-span-2\">\n");
      out.write("                    <input class=\"w-full rounded-[1.3rem] border border-market-line bg-market-cream px-5 py-4 text-lg outline-none\" type=\"text\" name=\"conditionsPaiement\" placeholder=\"Categorie ou conditions paiement\">\n");
      out.write("                </div>\n");
      out.write("                <button class=\"rounded-[1.3rem] bg-market-gold px-5 py-4 text-xl font-bold text-white\" type=\"submit\">Ajouter</button>\n");
      out.write("            </form>\n");
      out.write("        </section>\n");
      out.write("    </main>\n");
      out.write("</div>\n");
      out.write("<script>\n");
      out.write("    const sidebarToggle = document.getElementById('sidebarToggle');\n");
      out.write("    const appSidebar = document.getElementById('appSidebar');\n");
      out.write("    if (sidebarToggle && appSidebar) {\n");
      out.write("        sidebarToggle.addEventListener('click', () => {\n");
      out.write("            appSidebar.classList.toggle('-translate-x-full');\n");
      out.write("        });\n");
      out.write("    }\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /views/fournisseur/liste.jsp(11,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
      _jspx_th_c_005fset_005f0.setVar("activePage");
      // /views/fournisseur/liste.jsp(11,0) name = value type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true deferredMethod = false expectedTypeName = java.lang.Object methodSignature = null 
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/views/fournisseur/liste.jsp(11,0) 'suppliers'",_jsp_getExpressionFactory().createValueExpression("suppliers",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /views/fournisseur/liste.jsp(12,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
      _jspx_th_c_005fset_005f1.setVar("pageTitle");
      // /views/fournisseur/liste.jsp(12,0) name = value type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true deferredMethod = false expectedTypeName = java.lang.Object methodSignature = null 
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/views/fournisseur/liste.jsp(12,0) 'Gestion des Fournisseurs'",_jsp_getExpressionFactory().createValueExpression("Gestion des Fournisseurs",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f2_reused = false;
    try {
      _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f2.setParent(null);
      // /views/fournisseur/liste.jsp(13,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
      _jspx_th_c_005fset_005f2.setVar("pageSubtitle");
      // /views/fournisseur/liste.jsp(13,0) name = value type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true deferredMethod = false expectedTypeName = java.lang.Object methodSignature = null 
      _jspx_th_c_005fset_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/views/fournisseur/liste.jsp(13,0) 'Gerez vos relations partenaires et suivez vos approvisionnements en temps reel.'",_jsp_getExpressionFactory().createValueExpression("Gerez vos relations partenaires et suivez vos approvisionnements en temps reel.",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
      if (_jspx_th_c_005fset_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      _jspx_th_c_005fset_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f3(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f3 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f3_reused = false;
    try {
      _jspx_th_c_005fset_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f3.setParent(null);
      // /views/fournisseur/liste.jsp(14,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
      _jspx_th_c_005fset_005f3.setVar("sidebarBrand");
      // /views/fournisseur/liste.jsp(14,0) name = value type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true deferredMethod = false expectedTypeName = java.lang.Object methodSignature = null 
      _jspx_th_c_005fset_005f3.setValue(new org.apache.jasper.el.JspValueExpression("/views/fournisseur/liste.jsp(14,0) 'MarketPro UI'",_jsp_getExpressionFactory().createValueExpression("MarketPro UI",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f3 = _jspx_th_c_005fset_005f3.doStartTag();
      if (_jspx_th_c_005fset_005f3.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f3);
      _jspx_th_c_005fset_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f4(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f4 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f4_reused = false;
    try {
      _jspx_th_c_005fset_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f4.setParent(null);
      // /views/fournisseur/liste.jsp(15,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
      _jspx_th_c_005fset_005f4.setVar("sidebarSubtitle");
      // /views/fournisseur/liste.jsp(15,0) name = value type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true deferredMethod = false expectedTypeName = java.lang.Object methodSignature = null 
      _jspx_th_c_005fset_005f4.setValue(new org.apache.jasper.el.JspValueExpression("/views/fournisseur/liste.jsp(15,0) 'Terminal Admin v2.0'",_jsp_getExpressionFactory().createValueExpression("Terminal Admin v2.0",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f4 = _jspx_th_c_005fset_005f4.doStartTag();
      if (_jspx_th_c_005fset_005f4.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f4);
      _jspx_th_c_005fset_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f5(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f5 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f5_reused = false;
    try {
      _jspx_th_c_005fset_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f5.setParent(null);
      // /views/fournisseur/liste.jsp(16,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
      _jspx_th_c_005fset_005f5.setVar("topbarSearchPlaceholder");
      // /views/fournisseur/liste.jsp(16,0) name = value type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true deferredMethod = false expectedTypeName = java.lang.Object methodSignature = null 
      _jspx_th_c_005fset_005f5.setValue(new org.apache.jasper.el.JspValueExpression("/views/fournisseur/liste.jsp(16,0) 'Rechercher un fournisseur'",_jsp_getExpressionFactory().createValueExpression("Rechercher un fournisseur",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f5 = _jspx_th_c_005fset_005f5.doStartTag();
      if (_jspx_th_c_005fset_005f5.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f5);
      _jspx_th_c_005fset_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f6(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f6 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f6_reused = false;
    try {
      _jspx_th_c_005fset_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f6.setParent(null);
      // /views/fournisseur/liste.jsp(17,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
      _jspx_th_c_005fset_005f6.setVar("topbarSearchValue");
      // /views/fournisseur/liste.jsp(17,0) name = value type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true deferredMethod = false expectedTypeName = java.lang.Object methodSignature = null 
      _jspx_th_c_005fset_005f6.setValue(new org.apache.jasper.el.JspValueExpression("/views/fournisseur/liste.jsp(17,0) '${search}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${search}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f6 = _jspx_th_c_005fset_005f6.doStartTag();
      if (_jspx_th_c_005fset_005f6.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f6);
      _jspx_th_c_005fset_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f6, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /views/fournisseur/liste.jsp(22,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty flashMessage}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("            <div class=\"rounded-[1.6rem] border px-5 py-4 shadow-panel ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${flashType eq 'success' ? 'border-emerald-200 bg-emerald-50 text-emerald-700' : 'border-red-200 bg-red-50 text-red-700'}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\n");
          out.write("                <p class=\"text-sm font-semibold\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${flashMessage}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</p>\n");
          out.write("            </div>\n");
          out.write("        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /views/fournisseur/liste.jsp(98,24) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true deferredMethod = false expectedTypeName = java.lang.Object methodSignature = null 
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/views/fournisseur/liste.jsp(98,24) '${fournisseurs}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${fournisseurs}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /views/fournisseur/liste.jsp(98,24) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
      _jspx_th_c_005fforEach_005f0.setVar("f");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("                            <tr class=\"border-b border-market-line last:border-b-0\">\n");
            out.write("                                <td class=\"px-8 py-6\">\n");
            out.write("                                    <div class=\"flex items-center gap-5\">\n");
            out.write("                                        <div class=\"flex h-16 w-16 items-center justify-center rounded-full bg-market-mint text-2xl font-bold text-market-pine\">\n");
            out.write("                                            ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:substring(f.raisonSociale, 0, 1)}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:substring(f.raisonSociale, 1, 2)}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
            out.write("\n");
            out.write("                                        </div>\n");
            out.write("                                        <div>\n");
            out.write("                                            <p class=\"text-3xl font-semibold text-market-ink\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${f.raisonSociale}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\n");
            out.write("                                            <p class=\"mt-2 text-xl text-slate-500\">ID: FR-");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${f.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\n");
            out.write("                                        </div>\n");
            out.write("                                    </div>\n");
            out.write("                                </td>\n");
            out.write("                                <td class=\"px-8 py-6 text-2xl leading-10 text-market-ink\">\n");
            out.write("                                    <p>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${f.telephone}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\n");
            out.write("                                    <p class=\"text-slate-500\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${f.email}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\n");
            out.write("                                </td>\n");
            out.write("                                <td class=\"px-8 py-6\">\n");
            out.write("                                    <span class=\"rounded-full bg-market-mint px-4 py-2 text-2xl font-semibold text-market-pine\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${f.conditionsPaiement}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\n");
            out.write("                                </td>\n");
            out.write("                                <td class=\"px-8 py-6 text-3xl font-bold text-market-gold\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${f.delaiLivraisonJours}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\n");
            out.write("                                <td class=\"px-8 py-6\">\n");
            out.write("                                    <div class=\"flex flex-wrap gap-3\">\n");
            out.write("                                        <a class=\"rounded-full bg-market-gold px-4 py-2 text-lg font-bold text-white\" href=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/fournisseurs/commande?fournisseurId=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${f.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">Bon PDF</a>\n");
            out.write("                                        <a class=\"rounded-full bg-market-moss px-4 py-2 text-lg font-bold text-white\" href=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/fournisseurs/commande?fournisseurId=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${f.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&channel=email\">Email + PDF</a>\n");
            out.write("                                        <a class=\"rounded-full bg-market-pine px-4 py-2 text-lg font-bold text-white\" href=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/fournisseurs/modifier?id=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${f.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">Modifier</a>\n");
            out.write("                                        <form method=\"post\" action=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("/fournisseurs/supprimer\" onsubmit=\"return confirm('Supprimer ce fournisseur ?');\">\n");
            out.write("                                            <input type=\"hidden\" name=\"id\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${f.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\n");
            out.write("                                            <button class=\"rounded-full bg-red-500 px-4 py-2 text-lg font-bold text-white\" type=\"submit\">Supprimer</button>\n");
            out.write("                                        </form>\n");
            out.write("                                    </div>\n");
            out.write("                                </td>\n");
            out.write("                            </tr>\n");
            out.write("                        ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
}
