/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: jetty/12.0.7
 * Generated at: 2026-05-13 08:09:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.error;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class _500_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/views/partials/head.jspf", Long.valueOf(1778659006971L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"fr\">\n");
      out.write("<head>\n");
      out.write("    ");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,600;9..144,700;9..144,800&family=Manrope:wght@400;500;600;700;800&display=swap\" rel=\"stylesheet\">\n");
      out.write("<script src=\"https://cdn.tailwindcss.com\"></script>\n");
      out.write("<script>\n");
      out.write("    tailwind.config = {\n");
      out.write("        theme: {\n");
      out.write("            extend: {\n");
      out.write("                fontFamily: {\n");
      out.write("                    sans: ['Manrope', 'sans-serif'],\n");
      out.write("                    display: ['Fraunces', 'serif']\n");
      out.write("                },\n");
      out.write("                colors: {\n");
      out.write("                    market: {\n");
      out.write("                        cream: \"#f4f8ff\",\n");
      out.write("                        parchment: \"#e8f0ff\",\n");
      out.write("                        pine: \"#1f3fb7\",\n");
      out.write("                        moss: \"#2448d8\",\n");
      out.write("                        mint: \"#d7e6ff\",\n");
      out.write("                        gold: \"#f5a000\",\n");
      out.write("                        ember: \"#ff4d4f\",\n");
      out.write("                        ink: \"#171d2d\",\n");
      out.write("                        line: \"#d7e4ff\",\n");
      out.write("                        shell: \"#fbfdff\"\n");
      out.write("                    }\n");
      out.write("                },\n");
      out.write("                boxShadow: {\n");
      out.write("                    panel: \"0 20px 60px rgba(30, 64, 208, 0.08)\",\n");
      out.write("                    float: \"0 14px 40px rgba(30, 64, 208, 0.12)\"\n");
      out.write("                },\n");
      out.write("                borderRadius: {\n");
      out.write("                    shell: \"2rem\"\n");
      out.write("                },\n");
      out.write("                backgroundImage: {\n");
      out.write("                    \"market-grid\": \"radial-gradient(circle at 1px 1px, rgba(31,63,183,0.08) 1px, transparent 0)\",\n");
      out.write("                    \"market-glow\": \"radial-gradient(circle at top right, rgba(245,160,0,0.18), transparent 32%), radial-gradient(circle at bottom left, rgba(36,72,216,0.12), transparent 30%)\"\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("</script>\n");
      out.write("<style>\n");
      out.write("    ::selection {\n");
      out.write("        background: rgba(36, 72, 216, 0.22);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    body {\n");
      out.write("        font-family: Manrope, sans-serif;\n");
      out.write("        background-image:\n");
      out.write("            radial-gradient(circle at top, rgba(255,255,255,0.92), transparent 30rem),\n");
      out.write("            linear-gradient(180deg, #f7fbff 0%, #eff5ff 100%);\n");
      out.write("        color: #171d2d;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .glass-panel {\n");
      out.write("        background: rgba(255, 255, 255, 0.9);\n");
      out.write("        backdrop-filter: blur(18px);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .app-shell {\n");
      out.write("        min-height: 100vh;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .sidebar-link {\n");
      out.write("        display: flex;\n");
      out.write("        align-items: center;\n");
      out.write("        gap: 0.95rem;\n");
      out.write("        border-radius: 1.35rem;\n");
      out.write("        padding: 0.95rem 1rem;\n");
      out.write("        color: #262d42;\n");
      out.write("        transition: all 180ms ease;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .sidebar-link:hover {\n");
      out.write("        background: #eef4ff;\n");
      out.write("        color: #1f3fb7;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .sidebar-link.active {\n");
      out.write("        background: #d8e7ff;\n");
      out.write("        color: #1f3fb7;\n");
      out.write("        box-shadow: inset 0 0 0 1px rgba(31, 63, 183, 0.06);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .sidebar-icon {\n");
      out.write("        flex-shrink: 0;\n");
      out.write("        width: 1.45rem;\n");
      out.write("        height: 1.45rem;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .page-card {\n");
      out.write("        border-radius: 2rem;\n");
      out.write("        border: 1px solid #d7e4ff;\n");
      out.write("        background: rgba(255, 255, 255, 0.95);\n");
      out.write("        box-shadow: 0 20px 60px rgba(30, 64, 208, 0.08);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .metric-card {\n");
      out.write("        position: relative;\n");
      out.write("        overflow: hidden;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .metric-card::after {\n");
      out.write("        content: \"\";\n");
      out.write("        position: absolute;\n");
      out.write("        inset: auto -10% -45% auto;\n");
      out.write("        width: 8rem;\n");
      out.write("        height: 8rem;\n");
      out.write("        border-radius: 9999px;\n");
      out.write("        background: rgba(255,255,255,0.08);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .blue-scroll::-webkit-scrollbar {\n");
      out.write("        width: 8px;\n");
      out.write("        height: 8px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .blue-scroll::-webkit-scrollbar-thumb {\n");
      out.write("        background: rgba(31, 63, 183, 0.3);\n");
      out.write("        border-radius: 9999px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .blue-scroll::-webkit-scrollbar-track {\n");
      out.write("        background: rgba(215, 228, 255, 0.55);\n");
      out.write("    }\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("    <title>Erreur</title>\n");
      out.write("</head>\n");
      out.write("<body class=\"min-h-screen bg-market-cream text-slate-900\">\n");
      out.write("<main class=\"mx-auto flex min-h-screen w-full max-w-3xl items-center justify-center px-4\">\n");
      out.write("    <section class=\"w-full rounded-shell border border-market-pine/10 bg-white p-10 text-center shadow-panel\">\n");
      out.write("        <p class=\"text-sm font-bold uppercase tracking-[0.25em] text-market-ember\">Erreur 500</p>\n");
      out.write("        <h1 class=\"mt-4 text-4xl font-black text-market-pine\">Erreur interne</h1>\n");
      out.write("        <p class=\"mt-4 text-slate-500\">Une erreur est survenue pendant le traitement.</p>\n");
      out.write("    </section>\n");
      out.write("</main>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
