app.name=Gestion Supermarche

# SMS (optionnel)
sms.provider=twilio
sms.enabled=false
twilio.from.number=
twilio.account.sid=
twilio.auth.token=

# Mail
mail.enabled=true
mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.smtp.username=${MAIL_USERNAME}
mail.smtp.password=${MAIL_PASSWORD}
mail.smtp.from=SuperMarche <${MAIL_USERNAME}>