app.name=Gestion Supermarche

sms.provider=twilio
sms.enabled=false
twilio.from.number=
twilio.account.sid=
twilio.auth.token=

mail.enabled=false
mail.smtp.host=
mail.smtp.port=587
mail.smtp.username=
mail.smtp.password=
mail.smtp.from=
mail.smtp.auth=true
mail.smtp.starttls.enable=true
